title: Cool AF
brand: Cool AF
author: FerranC96
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Welcome to @Anukisima's and @FerranC96's personal blog;
  the place where we show the world the cool stuff we do!
baseurl: "/CoolAF" # the subpath of your site, e.g. /blog
aboutme: Welcome to <a href="https://www.instagram.com/anukisima/">@Anukisima</a>'s and <a href="https://twitter.com/ferranc96">@FerranC96</a>'s personal blog; the place where we show the world the cool stuff we do!.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
street-address: 1234 Somewhere Road
city: Any City
state-province: TX
postal-code: 09876
telephone: (555) 555-5555
current-year: 2019
page-1: # set with nav bar to say when to show class alert or not
page-2: #
page-3: #
show_excerpts: false # set to true to show excerpts on the homepage
# generate social links in footer
social_links:
#twitter: jekyllrb
#github:  jekyll
# rss: rss
# dribbble: jekyll
#facebook: GitHub
# flickr:   jekyll
instagram: cool.a.f
# linkedin: jekyll
# pinterest: jekyll
youtube: UCwi7V9DNkCKLouTjRAfs7fw
youtube_channel: UCwi7V9DNkCKLouTjRAfs7fw
# youtube_channel_name: CloudCannon
# telegram: jekyll
# googleplus: +jekyll
# microdotblog: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
author:
